# Generated by Django 3.2.5 on 2021-08-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=1)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparator.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comparator.product')),
            ],
        ),
    ]
